<?php
/**
 * Kapitchi Zend Framework 2 Modules
 *
 * @copyright Copyright (c) 2012-2014 Kapitchi Open Source Community (http://kapitchi.com/open-source)
 * @license   http://opensource.org/licenses/MIT MIT
 */ 
echo __FILE__ . ' Line: ' . __LINE__; var_dump($this->statusText);
echo __FILE__ . ' Line: ' . __LINE__; var_dump($this->statusCode);
echo __FILE__ . ' Line: ' . __LINE__; var_dump($this->errorDescription);
echo __FILE__ . ' Line: ' . __LINE__; var_dump($this->error);
echo __FILE__ . ' Line: ' . __LINE__; var_dump($this->errorUri);